# 头部菜单，title: link
menu:
  首页: /
  分类: /categories
  标签: /tags
  归档: /archives  
  关于: /about

# 是否显示目录
TOC: true

# 是否自动播放音乐
autoplay: false

# 默认音乐（随机播放）
mp3: 
  - https://link.hhtjim.com/163/1945857126.mp3
  - https://link.hhtjim.com/163/1420349595.mp3
  - https://link.hhtjim.com/163/28029509.mp3
  - http://link.hhtjim.com/163/425570952.mp3



# 首页封面图, 为空时取文章的cover作为封面(注意跨域问题,建议使用同源图片)
welcome_cover: /img/welcome-cover.jpg

# 默认文章封面图（随机调用,支持外链）
cover: 
  - /img/cover.jpg
  - /img/welcome-cover.jpg

# 是否显示Twitter分享卡片图像(图像尺寸要求：1200*600，creatorid不需要带@符号。注意：链接必须是完整url，否则Twitter将无法读取图片信息）
twitterpic:
  enable: false
  src: https://bangdream.moe/img/ident.png
  creatorid: yourtwitteridhere

# 是否使用mathjax
mathjax: false


# 是否关闭默认滚动条
scrollbar: true

# 本地搜索,请将索引文件放在网站根目录,或修改主题js文件的path值
local_search:
    # 是否启用
    enable: true

# 是否显示 一言(hitokoto)
hitokoto: true

# 链接(可选:facebook,twitter,github,wechat,email)
links:
    facebook: /
    twitter: /
    github: https://gitee.com/itvita
    wechat: /img/logo.png
    email: itvita@163.com
  
# 备案
beian: 
    # 是否显示备案信息
    enable: true
    # 是否在主页面最底下显示备案信息(虽然丑，但是完全满足规定要求)
    enableFooter: false
    # 备案号
    beianInfo: 豫ICP备2020032888号
    # 链接地址
    link: http://www.beian.miit.gov.cn

# Gitalk 评论插件（https://github.com/gitalk/gitalk）
gitalk:
    # 是否启用评论功能
    enable: true
    # 是否自动展开评论框
    autoExpand: true
    # 应用编号
    clientID: d1bce04390a8da2fa2ac
    # 应用秘钥
    clientSecret: 7194f621e1c1fa838710abd2a4a7ff05e4e511de
    # issue仓库名
    repo: site
    # Github名
    owner: itvita
    # Github名
    admin: ['itvita']
    # Ensure uniqueness and length less than 50
    id: location.pathname
     #GitHub issues的标签
    labels: ['Gitalk']
     #每页多少个评论
    perPage: 10
     #排序方式是从旧到新（first），还是从新到旧（last）
    pagerDirection: last
    #是否自动创建isssue，自动创建需要当前登录的用户为adminuser
    createIssueManually: true
    #是否启用快捷键(cmd|ctrl + enter) 提交评论
    distractionFreeMode: true

# 网站关键字
keywords: itvita

# 要使用google_analytics进行统计的话，这里需要配置ID
google_analytics: 

# 网站ico
favicon: /img/favicon.png

# rss文件
rss: atom.xml

# 要使用版权信息可以在这配置并设定许可方式，可以从 https://creativecommons.org/about/cclicenses/ 查询
copyright:
    enable: false
    license: "CC BY-NC-ND"
